CREATE TABLE PROBABILIDADES_J (

    ID NUMBER GENERATED ALWAYS AS IDENTITY,

    EVENTOS_FAVORABLES NUMBER NOT NULL,

    EVENTOS_POSIBLES NUMBER NOT NULL,

    RESULTADO NUMBER(10,4),

    FECHA_REGISTRO DATE DEFAULT SYSDATE,

    CONSTRAINT PK_PROBABILIDADES_J
    PRIMARY KEY(ID)

);

COMMIT;